/*  
 *  All rights reserved – Nex-G Exuberant Solutions Private Limited.                                                               
 *  File Name    : rlc_pdu_send.c                                                                                                  
 *  Module Name  : MAC-ES-E-IN                                                                                                          
 *  Project Name : MAC-ES-E UE Side                                                                                                 
 *  Description  : rlc layer data sending option                                                                                    
 *  Author       : Aniruddha Paul                                                                      
 *  Start date   : 26-11-2012                                                                                                       
 *  End date     : 04-12-2012                                                                                                                
 */

#include "../mac_es_e_include/header.h"
#include "../mac_es_e_include/structures.h"
#include "../mac_es_e_include/wrapper.h"
#define DEBUG

/*  
 *  Function Name  :      Main                                                                                               
 *  Purpose        :      Body of program starts from here                                                                     
 *  Input	   :	  Void	
 *  Return Value   :      integer type value                                                                                
 */

int
main (void)
{
  rlc_pdu_t *sdu;
  macd_pdu_mac_es *pdu;
  FILE *fp_sdu;
  FILE *fp_mac_sdu_log;
  char iteration = ONE;
  char segments = FOUR;

/* 
 * Function: malloc
 * Purpose : To provide dynamic memory on heap  
 * Inputs  : size of the memory needed
 * Return  : a pointer to the base address of the provided memory
*/

  sdu = (rlc_pdu_t *) nexg_malloc (sizeof (rlc_pdu_t));
  pdu = (macd_pdu_mac_es *) nexg_malloc (sizeof (macd_pdu_mac_es));

/*
 * Function: memset	   												             
 * Purpose : use to initialise  memory with a constant byte.    		  					           	
 * Inputs  : initialise address of memory,constant value we want to fill and size of memory .             		          
 * Return  : pointer to yhe memory area.                        				                              
 */

  nexg_memset (sdu, ZERO, sizeof (rlc_pdu_t));	/* The memset() function fills memory with a constant byte in sdu */
  nexg_memset (pdu, ZERO, sizeof (macd_pdu_mac_es));	/* The memset() function fills memory with a constant byte in pdu */

/* 
 * Function: fopen()
 * Purpose : To open a file 
 * Inputs  : file name & mode
 * Return  : a pointer to a structure of type FILE
*/
  fp_sdu = nexg_fopen ("../logfiles/rlc_pdu.txt", "rb");

  if (fp_sdu == NULL)		/* if starts to check error in opening file */
    {
      nexg_perror ("\t\t\tUnable to creat file\n");	/* to display a message supplied by the user along with the
						   errormessage generated by the system */
      return (ZERO);
    }

fp_mac_sdu_log = fopen ("../logfiles/mac_rcv.txt", "a");
      if (fp_mac_sdu_log == NULL)	/* if starts to check error in opening file */
	{
	  nexg_perror ("\t\t\tUnable to creat file\n");	/* to display a message supplied by the user along with the
							   errormessage generated by the system */
	  return (ZERO);
	}
/* 
 * Function: fread()
 * Purpose : To read data from a file 
 * Inputs  : pointer to the block of memory which receives data, size of the memory,no of items,file pointer 
 * Return  : no of items read from the file
*/

  while (nexg_fread (sdu, sizeof (rlc_pdu_t), ONE, fp_sdu) == ONE)
    {
      
      nexg_fprintf (fp_mac_sdu_log, "\t\t\t======>>>Waiting for the RLC layer<<<=====\n");	/* To print formatted output in file "mac_rcv.txt" */
      nexg_fprintf (fp_mac_sdu_log,
		    "\t\t\t======>>>Data receiving started at time=%s<<<======\n",
		    __TIME__);
      nexg_fprintf (fp_mac_sdu_log,
		    "\t\t\t======>>>Data receiving started on Date=%s<<<======\n",
		    __DATE__);

#ifdef DEBUG
      nexg_printf
	("\t\t ==============================================================================================\n");
      nexg_printf
	("\t\t||                                                                                             ||\n");
      nexg_printf
	("\t\t||                                 MAC-d TCTS ENTITY BEGINS.....                               ||\n");
      nexg_printf
	("\t\t||                                                                                             ||\n");
      nexg_printf
	("\t\t ==============================================================================================\n\n");
#endif

      nexg_fprintf (fp_mac_sdu_log,
		    "\t\t ==============================================================================================\n\n");
      nexg_fprintf (fp_mac_sdu_log,
		    "\t\t||                                                                                             ||\n");
      nexg_fprintf (fp_mac_sdu_log,
		    "\t\t||                                 MAC-d TCTS ENTITY BEGINS.....                               ||\n");
      nexg_fprintf (fp_mac_sdu_log,
		    "\t\t||                                                                                             ||\n");
      nexg_fprintf (fp_mac_sdu_log,
		    "\t\t ==============================================================================================\n\n");

      if (nexg_strcmp (sdu->cell_state, "CELL_FACH") == ZERO)	/* if starts to check MAC-SDU belongs to which entity  */
	{
	  nexg_fprintf (fp_mac_sdu_log,
			"\n************** MAC-SDU belongs to MAC-c/sh/m entity, C/T header is required*********************\n\n\n");
	  nexg_fprintf (fp_mac_sdu_log,
			"--------------Bit rate for CELL_FACH state : %d \n\n",
			sdu->bit_rate);
	  nexg_fprintf (fp_mac_sdu_log, "--------------C-RNTI : %hd \n\n",
			sdu->CRNTI);
	}
      else
	{
	  if (sdu->bit_rate <= SIXTY_FOUR)	/* else part of the if */
	    {
	      nexg_fprintf (fp_mac_sdu_log,
			    "\n****************************** MAC-SDU belongs to MAC-d entity******************************\n\n\n");
	      nexg_fprintf (fp_mac_sdu_log,
			    "--------------Bit rate for CELL_DCH state : %d \n\n",
			    sdu->bit_rate);
	      nexg_fprintf (fp_mac_sdu_log, "--------------C-RNTI : %hd \n\n",
			    sdu->CRNTI);
	    }
	  else			/* else part of the if */
	    {
	      nexg_fprintf (fp_mac_sdu_log,
			    "\n****************************** MAC-SDU belongs to MAC-e/es entity******************************\n\n");
	      nexg_fprintf (fp_mac_sdu_log,
			    "-----------------------------------No C/T header is required--------------------------------\n\n");

	      nexg_strcpy (pdu->mtext, sdu->mtext);
	      pdu->logical_channel = sdu->logical_channel;
	      pdu->bit_rate = sdu->bit_rate;
	      nexg_fprintf (fp_mac_sdu_log,
			    "\n************************** MACd PDU%d belongs to MAC-e/es entity***********************\n\n",
			    iteration);
	      nexg_printf
		("\n************************** MACd PDU%d belongs to MAC-e/es entity***********************\n\n",
		 iteration);
	      send_macd_pdu_mac_es (pdu);

	    }
	}
      iteration++;
    }

/*
 * Function:free.								                                                      	
 * Purpose : display amount of free and used memory in the system.							            
 * Inputs  : any pointer,which having allocted memory.                                                                             
 * Return  : nothing.						  	   		  			
 */
  free (sdu);
  free (pdu);

  nexg_fclose (fp_mac_sdu_log);
  nexg_fclose (fp_sdu);
#ifdef DEBUG
  nexg_printf
    ("..........................................ALL POINTERS ARE FREED....................................................\n");
#endif
}

/*************************************************************************************************************************************
*                                               end of file rlc_pdu_send.c                                                           *
************************************************************************************************************************************/
